leftnav:
- identifier: df251afe-45c8-a6a9-6f82-ae540b0f4274
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: a38f1985-d5a3-0fb5-ccc2-3f57664c1167
  name: Calendar
  pageRef: /pages/calendar
  weight: 20
- identifier: 9a134345-7ba1-20b8-500b-7dc6bdd548bc
  name: Readings
  pageRef: /pages/readings
  weight: 30
- identifier: 5502e4b6-eb0f-8058-7243-48791293e627
  name: Lecture Notes
  pageRef: /pages/lecture-notes
  weight: 40
- identifier: 9fa31ec0-ffc9-2a54-84c6-e47fa61f11dc
  name: Assignments
  pageRef: /pages/assignments
  weight: 50
- identifier: dc3b001c-a02c-edca-09e7-e65eb1dc662b
  name: Exams
  pageRef: /pages/exams
  weight: 60
- identifier: bd82f4d7-c304-9db7-b38e-d63a9fdb079a
  name: Study Materials
  pageRef: /pages/study-materials
  weight: 70
